name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Check and Install Az CLI
        run: |
          if ! command -v az &> /dev/null
          then
            echo "Az CLI not found. Installing..."
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          fi
        shell: bash
      
      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az account show
            az storage -h

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=img_webui
          IMAGE_TAG=v1.0.0
          ACR_NAME=djibyacr
          ACR_LOGIN_SERVER=$ACR_NAME.azurecr.io

          # Build the Docker image
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

          # Tag the Docker image
          docker tag $IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

          # Login to ACR
          az acr login --name $ACR_NAME

          # Push the Docker image to ACR
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG